source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CMLibrary_Example', :exclusive => true do
  pod "CMLibrary", :path => "../"
end

target 'CMLibrary_Tests', :exclusive => true do
  pod "CMLibrary", :path => "../"

  
end
